Add security support to webhook plugin
ansible/event-driven-ansible pull request #106
Opened 2023-03-15 20:23 UTC by bzwei

Client needs to send an bearer authorization token. Enable TLS support if a certificate file is provided.

Resolves AAP-4826: Add security check for webhook and alert manger's local server

2023-03-16 10:27 UTC, ttuffin submitted a review, later dismissed
Tested, works ok. In a follow up PR it might be good to catch SSL exceptions to provide a clearer message, i.e when the cert and key do not match.

2023-03-16 10:41 UTC, Alex-Izquierdo requested changes

2023-03-16 10:41 UTC, Alex-Izquierdo commented on plugins/event_source/webhook.py
> +    app["token"] = args["token"]
I really believe this param should be optional. First to keep the backward compatibility and also not all the clients are able to send the token.

2023-04-17 16:26 UTC, Alex-Izquierdo submitted a review, later dismissed
lgtm

2023-05-01 14:45 UTC, hsong-rh approved these changes

2023-05-02 13:17 UTC, ttuffin approved these changes

2023-05-02 13:17 UTC, merged