remove systemd-python from pypi requirements and list in bindep
ansible/event-driven-ansible pull request #154
Opened 2023-07-24 20:09 UTC by thedoubl3j

systemd-python is not available on pip, this causes issues when a user attempts to build an EE from the collection. the package is available via dnf so moving the dependency to a bindep.txt will pass the dep to dnf during the ansible-builder build phase which will be able to resolve the dep. see #153 for more context on the issue

2023-07-24 20:40 UTC, benthomasson approved these changes

2023-07-24 20:52 UTC, bzwei approved these changes

2023-07-24 21:12 UTC, Alex-Izquierdo requested changes
I don't think to say that systemd-package is unavailable on pypi or wrong packaged is correct. As is described in the docs, it just  needs to have installed several system dependencies. 

As this process is complicated, I agree with remove it from the requirements.txt. But the readme must indicate that `python3-systemd` package must be installed in addition to the requirements.txt.

2023-07-24 21:16 UTC, Alex-Izquierdo requested changes

2023-07-24 21:16 UTC, Alex-Izquierdo commented on bindep.txt
> +systemd-python
According [to the documentation](https://github.com/systemd/python-systemd#installation) and my own tests, the package name is `python3-systemd`

2023-07-26 19:26 UTC, Alex-Izquierdo commented
Hi @thedoubl3j thanks for your contribution and update the right package name. Readme needs to be modified too, to indicate that `python3-systemd` package must be installed, otherwise the users that follow these instructions would have unexpected errors.

2023-07-28 01:55 UTC, thedoubl3j commented
@Alex-Izquierdo done and squashed commits as well

2023-07-28 09:24 UTC, konstruktoid commented on README.md
> +The binary module dependencies are not installed by ansible-galaxy. They must also  be installed manually using dnf:
Write a generic instruction or add additional instructions using other package managers as well?

2023-07-28 09:41 UTC, Alex-Izquierdo commented on README.md
> +
IMO this test is clearer:
```suggestion
To use the journald source plugin, it is also necessary to have the system package named `python3-systemd` installed on Debian or Fedora operating systems. For other platforms, loot at the [systemd-python documentation](https://github.com/systemd/python-systemd#installation). 
```

2023-08-02 12:03 UTC, Alex-Izquierdo commented on README.md
> +
Hi @thedoubl3j Do you agree to commit my suggestion?

2023-09-28 17:13 UTC, Alex-Izquierdo commented
package python3-systemd must be installed as well in the CI workflows to pass the tests.

2024-08-06 07:45 UTC, closed without merging

2024-08-06 07:45 UTC, ssbarnea commented
While use of `bindep.txt` seems nice (i wanted to add it myself), I am closing this because referred bug was incorrect. Note that I am in favour of adding a bindep.txt fine, but if we do, it must be accompanied by some GHA/tox changes that would be testing it for supported platforms.