Enable changelogs for collection
ansible/event-driven-ansible pull request #230
Opened 2024-08-06 14:51 UTC by Akasurde

##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE

- Docs Pull Request

2024-08-07 15:09 UTC, alinabuzachis approved these changes

2024-08-15 08:20 UTC, ssbarnea requested changes
While I find it useful, I am not seeing this being used by any GHA jobs, so I have no confidence that these settings are working.

Please ensure that we have a way to test them on CI.

2024-08-15 17:09 UTC, Akasurde commented
I think these are standard changelog settings. These will be used at the time of release. I tried them locally and they work.

2024-08-16 13:42 UTC, ssbarnea requested changes
I started to work on it but I faced some problems like https://github.com/ansible-community/antsibull-changelog/issues/172 
and I had to stop.

We should not merge this unless we can validate that we can build/test these fragments.

2024-08-16 14:33 UTC, felixfontein commented on changelogs/.plugin-cache.yaml
Don't check this file in. Add it to `.gitignore` instead.

2024-08-16 14:33 UTC, felixfontein commented on .pre-commit-config.yaml
> +    - id: antsibull-changelog-lint-changelog-yaml
If you lint `changelogs/changelog.yaml`, you also need to add that file. Otherwise linting it will fail.

2024-08-27 19:58 UTC, merged