[WIP] Credential type
ansible/event-driven-ansible pull request #240
Opened 2024-08-08 14:08 UTC by alinabuzachis

2024-08-12 23:53 UTC, Akasurde commented
@alinabuzachis Can you please rebase this branch? Thanks.

2024-08-13 16:44 UTC, Akasurde requested changes

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type.py
> +  - This module allows to create, update or delete a credential type in EDA controller.
```suggestion
  - This module allows the user to create, update or delete a credential type in the EDA controller.
```

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type.py
> +  - The 'requests' Python module must be installed.
```suggestion
```

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type.py
> +    choices: ["present", "absent", "exists"]
Let us drop state `exists`.

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type_info.py
> +  - The 'requests' Python module must be installed.
```suggestion
```

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type_info.py
> +RETURN = """ # """
Let us populate this information.

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type_info.py
> +        result = controller.get_one_or_many(
Can you please handle cases where - 
1. Credential type name is provided but none is present 
2. Credential type is returned as dict

```
    if result is None:
        result = []
    if not isinstance(result, list):
        result = [result]
```

2024-08-13 16:44 UTC, Akasurde commented on plugins/modules/credential_type_info.py
> +    module.exit_json(result=result)
Let us return something meaningful such as `credential_types=result`, what do you think?

2024-08-14 17:49 UTC, Akasurde submitted a review, later dismissed

2024-08-15 19:12 UTC, resoluteCoder approved these changes

2024-08-15 20:34 UTC, Akasurde approved these changes

2024-08-15 20:51 UTC, merged