ADD scm_branch to project module
ansible/event-driven-ansible pull request #364
Opened 2024-11-26 09:57 UTC by chris93111

allow override scm_branch to project module

2025-01-17 13:23 UTC, alinabuzachis reviewed
@chris93111 Thank you for working on this feature. Can you also please add an integration test for this new functionality?

2025-01-17 13:23 UTC, alinabuzachis commented on plugins/modules/project.py
> +      type: str
Can you please add `version_added: 2.4.0`?

2025-01-20 01:09 UTC, chris93111 commented on plugins/modules/project.py
> +      type: str
added

2025-01-20 01:12 UTC, chris93111 commented on plugins/modules/project.py
> +      type: str
integration test added , the target branch is stable-1.1

2025-01-21 11:31 UTC, alinabuzachis approved these changes

2025-01-21 11:51 UTC, Alex-Izquierdo commented on tests/integration/targets/project/tasks/scm_branch.yml
> +    - name: Wait for project sync
I would say that not even we need to check if the backend imports the project, we just need to check that has been created with the expected branch.

2025-01-21 11:52 UTC, Alex-Izquierdo requested changes

2025-01-21 11:52 UTC, Alex-Izquierdo commented on tests/integration/targets/project/tasks/scm_branch.yml
It should have also a test to check that the module can edit the branch of a existing project.

2025-01-21 11:53 UTC, Alex-Izquierdo commented
@chris93111 Thank you very much for your contribution and attending our comments.

2025-01-21 11:59 UTC, chris93111 commented on tests/integration/targets/project/tasks/scm_branch.yml
> +    - name: Wait for project sync
ok i changed to until

2025-01-21 11:59 UTC, chris93111 commented on tests/integration/targets/project/tasks/scm_branch.yml
ok, i have added test with edit branch

2025-01-28 13:30 UTC, alinabuzachis submitted a review, later dismissed

2025-01-30 10:20 UTC, alinabuzachis commented
@chris93111 Can you please fix the cspell issue 
`plugins/modules/project.py:93:18 - Unknown word (devel)`

I think the addition of the word devel to this document https://github.com/ansible/event-driven-ansible/blob/main/.config/dictionary.txt will fix it.

2025-01-30 10:21 UTC, alinabuzachis commented
@chris93111  Could you also make sure that the integration tests pass? Thanks.

2025-02-08 11:54 UTC, chris93111 commented
> @chris93111 Can you please fix the cspell issue `plugins/modules/project.py:93:18 - Unknown word (devel)`
> 
> I think the addition of the word devel to this document https://github.com/ansible/event-driven-ansible/blob/main/.config/dictionary.txt will fix it.

Hi ok is added

2025-02-12 19:05 UTC, alinabuzachis commented
@chris93111 I apologise, but I accidentally closed the PR. I re-opened it and it should be fine.

2025-02-12 19:11 UTC, alinabuzachis commented
@chris93111 I'm seeing this error in the integration tests:
```

TASK [project : Define variables for credential and decision environment] ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [testhost]: FAILED! => {"changed": false, "msg": "The variable name 'scm_branch:' is not valid. Variables must start with a letter or underscore character, and contain only letters, numbers and underscores."}
```

2025-04-30 10:35 UTC, Alex-Izquierdo requested changes

2025-04-30 10:35 UTC, Alex-Izquierdo commented on plugins/modules/project.py
> +      version_added: 2.4.0
this should be updated to 2.8.0

2025-04-30 14:20 UTC, chris93111 commented on plugins/modules/project.py
> +      version_added: 2.4.0
changed

2025-05-02 19:45 UTC, chris93111 commented
Hi, @Alex-Izquierdo can you review ?

2025-05-05 19:28 UTC, chris93111 commented
> Hi @chris93111 Thanks a lot for your effort. Looks good to me, but there is a test which is not passing. I think it is a bug in the playbook test where you are using the wrong reference: https://github.com/ansible/event-driven-ansible/pull/364/files#diff-c258b119d585839bf5264e232ea5a164b312f75075cd3c1bbee50f027be0ef2cR49

@Alex-Izquierdo  ok fixed

2025-05-05 20:34 UTC, Alex-Izquierdo approved these changes
LGTM, thank you very much!

2025-05-05 20:41 UTC, Dostonbek1 approved these changes

2025-05-05 20:42 UTC, merged