Update docs for CLI installer
ansible/event-driven-ansible pull request #54
Opened 2022-11-14 08:01 UTC by ttuffin

2022-11-14 09:18 UTC, Alex-Izquierdo requested changes

2022-11-14 09:18 UTC, Alex-Izquierdo commented on README.md
> +`ansible-playbook -i localhost, -c local ansible.eda.install_rulebook_cli -K`
`-K` is not required as there are multiple ways to provide the credentials or even it could be not necessary (e.g. a passwordless sudoer)

2022-11-14 09:18 UTC, Alex-Izquierdo commented on README.md
> +**Note:** Some tasks in this role require privilege escalation and therefore you will need to provide the necessary credentials.
```suggestion
**Note:** Some tasks in this role require [privilege escalation](https://docs.ansible.com/ansible/latest/plugins/become.html) and therefore you may need to provide the necessary credentials.
```

2022-11-14 09:22 UTC, Alex-Izquierdo commented on playbooks/install_rulebook_cli.yml
> +# ansible-playbook  install_rulebook_cli.yml -c local -i localhost, -K
same as above.

2022-11-14 16:07 UTC, Alex-Izquierdo approved these changes
lgtm

2022-11-22 14:42 UTC, bzwei approved these changes

2022-11-22 14:42 UTC, merged