Allow installation of collection from source
ansible/event-driven-ansible pull request #64
Opened 2022-12-19 12:18 UTC by ttuffin

As discussed in PR #63, we want to allow for the installation of the EDA collection from the source repo. This will allow us to work around issues such as hitting Galaxy API limits in our workflows.

2022-12-21 15:26 UTC, Alex-Izquierdo requested changes

2022-12-21 15:26 UTC, Alex-Izquierdo commented on roles/install_ansible_rulebook/tasks/main.yml
> +  ansible.builtin.command: ansible-galaxy collection install {{ eda_collection_pkg_name }} community.general
Enclose everything in quotes to avoid potential issues with jinja templating.

2022-12-22 11:32 UTC, Alex-Izquierdo approved these changes

2022-12-22 15:18 UTC, bzwei approved these changes

2022-12-22 20:50 UTC, merged